### ISSUE TITLE
Miner fails to run cause algo

### ISSUE THREAD

**Issue by maybeti8ame** [esrrhs/go-cpuminer#3]
I run the miner , but it failed cause the algo. it seems the server responses `randomx/0`?
```
go-cpuminer -server pool.hashvault.pro:80 -user *** --pass x -algo cn-heavy/xhv
[INFO] [2022-05-22T12:12:34.284312511Z] [main.go:52] [main.main] start...
[INFO] [2022-05-22T12:12:34.324437599Z] [stratum.go:65] [main.(*Stratum).Reconnect] Stratum New start Using user *** pass x pool pool.hashvault.pro:80
[INFO] [2022-05-22T12:12:34.422070944Z] [stratum.go:78] [main.(*Stratum).Reconnect] Stratum pool connect ok xxx:51572->131.153.76.130:80
[INFO] [2022-05-22T12:12:34.422291186Z] [stratum.go:347] [main.(*Stratum).login] Stratum start login...
[INFO] [2022-05-22T12:12:34.422477514Z] [stratum.go:58] [main.NewStratum] Stratum New ok
[INFO] [2022-05-22T12:12:34.422645168Z] [stratum.go:93] [main.(*Stratum).listen] Stratum Starting Listener
[INFO] [2022-05-22T12:12:34.520259297Z] [stratum.go:293] [main.(*Stratum).parseExtensions] Stratum parseExtensions unknow motd
[INFO] [2022-05-22T12:12:34.520486641Z] [stratum.go:277] [main.(*Stratum).parseJob] Stratum parseJob ok id=ddfdd9f1-5c7b-43c2-b88e-03c1eff9d463 algo=randomx/0 height=2628981 target=512409557603043 diff=36000
[INFO] [2022-05-22T12:12:34.520585977Z] [stratum.go:224] [main.(*Stratum).handleLogin] Stratum handleLogin ok
[INFO] [2022-05-22T12:12:34.520681646Z] [miner.go:117] [main.(*Miner).dispatch] Miner setJob ok id=ddfdd9f1-5c7b-43c2-b88e-03c1eff9d463 algo=randomx/0 height=2628981 target=512409557603043 diff=36000

[ERROR] [2022-05-22T12:12:34.524663598Z] [error.go:22] [github.com/esrrhs/go-engine/src/common.CrashLog] crash runtime error: slice bounds out of range [24:0] 
=== BEGIN goroutine stack dump ===
goroutine 13 [running]:
github.com/esrrhs/go-engine/src/common.DumpStacks(0x8f8120, 0x9469e0)
	/root/go/src/github.com/esrrhs/go-engine/src/common/error.go:30 +0x6d
github.com/esrrhs/go-engine/src/common.CrashLog()
	/root/go/src/github.com/esrrhs/go-engine/src/common/error.go:22 +0xbf
panic(0x9469e0, 0xc000024540)
	/usr/local/go/src/runtime/panic.go:969 +0x166
main.(*Worker).start(0xc00000e5e0)
	/root/go/src/github.com/esrrhs/go-cpuminer/worker.go:54 +0x4b1
main.NewMiner.func1(0xc00000e5e0)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:62 +0x4d
created by main.NewMiner
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:60 +0x226

goroutine 1 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:188 +0xba
main.(*Miner).Run(0xc000060780)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:95 +0x89
main.main()
	/root/go/src/github.com/esrrhs/go-cpuminer/main.go:117 +0x765

goroutine 6 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:188 +0xba
github.com/esrrhs/go-engine/src/common.Sleep(0x1)
	/root/go/src/github.com/esrrhs/go-engine/src/common/time.go:37 +0x52
github.com/esrrhs/go-engine/src/common.updateNowInSecond()
	/root/go/src/github.com/esrrhs/go-engine/src/common/time.go:23 +0x52
created by github.com/esrrhs/go-engine/src/common.init.1
	/root/go/src/github.com/esrrhs/go-engine/src/common/time.go:11 +0x66

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7f7456338f18, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0000ac518, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000ac500, 0xc00014e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000ac500, 0xc00014e000, 0x1000, 0x1000, 0xc00015dd90, 0x87bd75, 0x8c71e0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010118, 0xc00014e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
bufio.(*Reader).fill(0xc0000609c0)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadSlice(0xc0000609c0, 0xa, 0x0, 0x0, 0x8c7101, 0x8c66e0, 0xc000022b18)
	/usr/local/go/src/bufio/bufio.go:359 +0x3d
bufio.(*Reader).ReadBytes(0xc0000609c0, 0xa, 0xc000022ad8, 0x3, 0xc00005e200, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:438 +0x7a
bufio.(*Reader).ReadString(...)
	/usr/local/go/src/bufio/bufio.go:475
main.(*Stratum).listen(0xc000081e10)
	/root/go/src/github.com/esrrhs/go-cpuminer/stratum.go:96 +0x9e
created by main.NewStratum
	/root/go/src/github.com/esrrhs/go-cpuminer/stratum.go:56 +0x1cd

goroutine 8 [sleep]:
time.Sleep(0x34630b8a000)
	/usr/local/go/src/runtime/time.go:188 +0xba
github.com/esrrhs/go-engine/src/loggo.loopCheck(0x1, 0x9830b1, 0xa, 0x3, 0x0, 0x0, 0x0)
	/root/go/src/github.com/esrrhs/go-engine/src/loggo/loggo.go:352 +0x85
created by github.com/esrrhs/go-engine/src/loggo.Ini
	/root/go/src/github.com/esrrhs/go-engine/src/loggo/loggo.go:61 +0x128

goroutine 14 [chan receive]:
main.(*Miner).dispatch(0xc000060780)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:111 +0x247
main.NewMiner.func2(0xc000060780)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:68 +0x4d
created by main.NewMiner
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:66 +0x31f

goroutine 15 [chan receive]:
main.(*Miner).commit(0xc000060780)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:102 +0x32
main.NewMiner.func3(0xc000060780)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:73 +0x4d
created by main.NewMiner
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:71 +0x344

goroutine 16 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/usr/local/go/src/os/signal/signal.go:127 +0x44

goroutine 19 [chan receive]:
main.main.func2(0xc000060ae0, 0xa34de0, 0xc000060780)
	/root/go/src/github.com/esrrhs/go-cpuminer/main.go:112 +0x5a
created by main.main
	/root/go/src/github.com/esrrhs/go-cpuminer/main.go:110 +0x74e

=== END goroutine stack dump ===
panic: runtime error: slice bounds out of range [24:0] [recovered]
	panic: runtime error: slice bounds out of range [24:0]

goroutine 13 [running]:
github.com/esrrhs/go-engine/src/common.CrashLog()
	/root/go/src/github.com/esrrhs/go-engine/src/common/error.go:24 +0x207
panic(0x9469e0, 0xc000024540)
	/usr/local/go/src/runtime/panic.go:969 +0x166
main.(*Worker).start(0xc00000e5e0)
	/root/go/src/github.com/esrrhs/go-cpuminer/worker.go:54 +0x4b1
main.NewMiner.func1(0xc00000e5e0)
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:62 +0x4d
created by main.NewMiner
	/root/go/src/github.com/esrrhs/go-cpuminer/miner.go:60 +0x226
```

**Comment by esrrhs** [comment]
yes. it don't support randomx/0

**Comment by maybeti8ame** [comment]
but i have set the option algorithm to cn-heavy/xhv, the server still responses randomx/0?

**Comment by esrrhs** [comment]
maybe the server change the mining algo
